### ISSUE TITLE
Documentation for delete-fields is wrong

### ISSUE THREAD

**Issue by stefanjudis** [felixjung/contentful-utils#7]
Hey hey,

cool stuff, you're doing here. I spotted a mistake in the readme though.

https://github.com/felixjung/contentful-utils#deleting-fields

Looks like a copy and paste mistake. :) 

I would fix it myself but I'm not sure how the command works ( https://github.com/felixjung/contentful-utils#delete-fields-options doesn't explain well enough I guess)

Thanks and keep it going.

**Comment by felixjung** [comment]
Ohai! Just saw this issue 😆 Will fix asap.

**Comment by felixjung** [comment]
Fixed thanks. I will improve the documentation with future releases. Still figuring out how to best create CLI help output.

**Comment by felixjung** [comment]
Published in v1.0.5.
